services:
  web: 
    container_name: web-2024
    image: kubedevio/rotten-potatoes:v1
    ports:
      - "8080:5000"
    networks:
      - observability
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongodb-2024"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "m0ngopwd!"
  mongodb:
    container_name: mongodb-2024
    image: mongo:7.0
    volumes:
      - db_mongo:/data/db
    networks:
      - observability
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongouser"
      MONGO_INITDB_ROOT_PASSWORD: "m0ngopwd!"
  prometheus:
    container_name: prometheus-2024
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
    networks:
      - observability
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      host.docker.internal: ${DOCKER_HOST}
    env_file:
      - .env

  grafana:
    container_name: grafana-2024
    image: grafana/grafana:10.2.2
    ports:
      - "9000:3000"
    networks:
      - observability

volumes:
  db_mongo:
networks:
  observability:
    driver: bridge
